<a href="https://colab.research.google.com/github/GabrielDantas-99/AnaliseDeDados/blob/main/EstudoCientistaDeDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Funções

In [ ]:
# Funcao sem parametro
def funcao():
    print("Olá")
funcao()

Olá


In [ ]:
# Funcao com parametro
def funcao(frase):
    print(frase)
funcao("olá")

olá


In [ ]:
# Funcao Default
def funcao(inic=1, fim=10):
    for i in range(inic, fim+1):
        print(i)
print("Sem alterar:")
funcao() # Os parametros serao setados como default
print("Alterando os Default:")
funcao(2, 8)

# Listas

In [ ]:
# Formas de criar listas:
lista = [1, 2, 4, 6]
print(lista)
print(type(lista))

In [ ]:
# Lista com lista
lista2 = [1, [1,2,3,4], True]
print(lista2[1][2])
print(lista2)

In [ ]:
# Criando lista com range
lista3 = list(range(10,100, 4))
print(lista3)

In [ ]:
# Comprimento de uma lista
print(len(lista3))

In [ ]:
# Acessando itens de uma lista
print(lista3)
# Acessando posição 3
print(lista3[8])
# Alterando dado de uma posição
lista3[5] = 999
print(lista3)

In [ ]:
# Adionando um dado na lista
lista3.append(10)
print(lista3)

In [ ]:
# Percorrendo uma lista
for n in range(0, len(lista3)):
    print(lista3[n])

In [ ]:
print(lista3[1:4:])

# Dicionários (Chave:Valor)

In [ ]:
# Declarando um dicionario
notas = {'Joao' : 6.0, 'Maria' : 8.0, 'Pedro' : 6.5}
print(notas)

In [ ]:
# Sabendo quais as chaves sao acessiveis no dicionario
notas.keys()

In [ ]:
# Sabendo todos os valores acessiveis no dicionario
notas.values()

In [ ]:
# Acessando um valor unico no dicionario
print(notas['Joao'])

In [ ]:
# Verificando a existencia de uma chave
print('Joao' in notas)
print('Fernando' in notas)

In [ ]:
# Adicionando um novo elemento(chave/valor) no dicionario
notas['Ana'] = 9.0 # Valor é sempre adicionado ao final do dicionario
print(notas)

In [ ]:
# Apagando um elemento do dicionario
del notas['Joao']
print(notas)

In [ ]:
# Buscando um valor, caso não encontre mostra segundo parametro
notas.get('Geraldo', "Não Encontrado")
notas.get('Ana', "Não Encontrado")

'Não Encontrado'

# Sets: Conjuntos não ordenados de elementos não repetidos

In [ ]:
bigdata = {'Spark', 'Hive', 'Sqoop'}
print(type(bigdata))

In [ ]:
# Verificando a existencia de um valor no set
print('Spark' in bigdata)

In [ ]:
# Adicionando elemento
bigdata.add('Hadoop') # É adicionado no inicio do set
bigdata

In [ ]:
# Verificando o tamanho do set
print(len(bigdata))

In [ ]:
# Tentando adicionar um mesmo elemento existente no set
bigdata.add('Spark') # Não ocorre nada pq sets não possui elementos repetidos
bigdata

# Tuplas: Listas que nao podem ser alteradas

In [ ]:
# Declarando uma tupla
tupla = (1, 2, 3, 5, 6, 7)

In [ ]:
# Acessando um item na tupla
tupla[4]

In [ ]:
# Dicionario em que cada posição recebe uma tupla
dic1 = {(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4}
dic1

# Numpy

In [ ]:
# Importando o Numpy
import numpy as np

In [ ]:
# Criando uma matriz unidimensional
unid = np.array([12, 24, 26, 18, 10])
print(unid)
print(type(unid))

[12 24 26 18 10]
<class 'numpy.ndarray'>


In [ ]:
# Criando arrays e setando seus types
arfloat = np.array([1.3, 4.2, 6.4], dtype = np.float64) # Tipo float
print(arfloat); print(type(arfloat))
arint = np.array([1, 3, 5], dtype = np.int32) # Tipo inteiro
print(arint); print(type(arint))

[1.3 4.2 6.4]
<class 'numpy.ndarray'>
[1 3 5]
<class 'numpy.ndarray'>


In [ ]:
# Mudando o tipo do array astype
mtnew = np.array([1.4, 3.6 -5.1, 9.42])
print(mtnew)
newmtint = mtnew.astype(np.int32)
print(newmtint)
oldmtint = newmtint.astype(np.float64)
print(oldmtint)

[ 1.4  -1.5   9.42]
[ 1 -1  9]
[ 1. -1.  9.]


In [ ]:
# Estrutura Bidimensional
mt7 = np.array([[7,2,4], [6,4,1], [9,6,3]])
print(mt7)
# Acessando elemento especifico
print(mt7[0][1])
# Tamanho das dimensões da matriz
print(mt7.shape)

[[7 2 4]
 [6 4 1]
 [9 6 3]]
2
(3, 3)


In [ ]:
# Funções matematicas
print(mt7.max()) # Valor máximo
print(mt7.min()) # Valor minimo 
print(mt7.sum()) # Soma os valores
print(mt7.mean()) # Media dos valores
print(mt7.std()) # Desvio padrao 

9
1
42
4.666666666666667
2.4037008503093262


In [ ]:
# Criando arrays vazios tipificados
vazio = np.empty([3,2], dtype=int) # Empty: não são inicializados, mas nao sao vazios
vazio

[[93926019753424              0]
 [             0              0]
 [             0              0]]


In [ ]:
# Criando uma matriz 4x3 com valores 0
zeros = np.zeros([4,3]) # Com valores igual a um: np.ones([])
zeros

In [ ]:
# Criando uma matriz com diagonal principal com valores 1
diagonal = np.eye(5)
diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Valores aleatorios entre 0 e 1
n2 = np.random.random((5))
print(n2)
# Numero aleatorios com distruição normal contendo negativos
n3 = np.random.randn((5))
print(n3)

[0.05291357 0.46908585 0.83954674 0.13405788 0.70333769]
[-0.97191479 -1.16039573 -0.80705945  1.88519252 -1.00177526]


In [ ]:
# Multiplicando array aleatorio 3 x 4
ar2 = 10 * np.random.random((3,4))
print(ar2)

[[2.36013627 3.4376349  9.11736689 3.72149563]
 [9.97912876 3.92711018 0.74904018 8.00414144]
 [9.5013769  4.09611521 7.84587225 3.63170425]]


In [ ]:
# Gerando numeros aleatorios com uso de semente(Mesmos nums ale nas execuções)
gnr = np.random.default_rng(1) # Ao mudar esse numero serao gerados outrs aleatorios
ale5 = gnr.random(3)
print(ale5)

# Gerando inteiros
ale6 = gnr.integers(10, size = (3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [ ]:
# Removendo repetições 
j = np.array([11, 12, 13, 14, 15, 16, 13, 11, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 20]


In [ ]:
# Adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
m = np.array([[5, 6], [7, 8]])
soma = n + m
print(soma)
print('-------')
multiplicacao = n * m
print(multiplicacao)
print('-------')
o = np.array([2, 4])
mult = m * o
print(mult)

[[ 6  8]
 [10 12]]
-------
[[ 5 12]
 [21 32]]
-------
[[10 24]
 [14 32]]


In [ ]:
# Transposição com o método T
f = np.arange(15).reshape(3, 5)
print(f)
print('-------')
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
# Expressões lógicas
v = np.random.randn(4, 4)
print(v)
# Criando matriz de valores bool baseada no array v
x = v > 0
print(x)
# Criando matriz com 1 e -1 baseada nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-1.30074309e+00  9.09684715e-01 -7.09541044e-01 -6.14970018e-01]
 [-1.05757344e+00  1.59529735e+00  6.23606676e-01  6.52759202e-01]
 [-5.46906963e-01  3.61861443e-02  2.81054884e-01 -7.67948153e-02]
 [-3.75550559e-01  7.57380522e-01  4.81683882e-01  7.47604635e-04]]
[[False  True False False]
 [False  True  True  True]
 [False  True  True False]
 [False  True  True  True]]
[[-1  1 -1 -1]
 [-1  1  1  1]
 [-1  1  1 -1]
 [-1  1  1  1]]


## Pandas

In [42]:
import pandas as pd

In [45]:
dados = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/FormacaoCientistaDados/Credit.csv")
dados.shape

(1000, 21)

In [46]:
# Estatisticas de colunas numericas
dados.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [47]:
# Primeiros registros
dados.head()

checking_status  duration                    credit_history  \
0              <0         6  'critical/other existing credit'   
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'        >=7   
1             radio/tv           5951                <100     1<=X<4   
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

In [48]:
# Ultimos registros
dados.tail()

checking_status  duration                    credit_history  \
995   'no checking'        12                   'existing paid'   
996              <0        30                   'existing paid'   
997   'no checking'        12                   'existing paid'   
998              <0        45                   'existing paid'   
999        0<=X<200        45  'critical/other existing credit'   

                 purpose  credit_amount savings_status  employment  \
995  furniture/equipment           1736           <100      4<=X<7   
996           'used car'           3857           <100      1<=X<4   
997             radio/tv            804           <100         >=7   
998             radio/tv           1845           <100      1<=X<4   
999           'used car'           4576     100<=X<500  unemployed   

     installment_commitment       personal_status other_parties  ...  \
995                       3  'female div/dep/mar'          none  ...   
996                       4        'male div/sep'          none  ...   
997                       4         'male single'          none  ...   
998                       4         'male single'          none  ...   
999                       3         'male single'          none  ...   

      property_magnitude age  other_payment_plans     housing  \
995        'real estate'  31                 none         own   
996     'life insurance'  40                 none         own   
997                  car  38                 none         own   
998  'no known property'  23                 none  'for free'   
999                  car  27                 none         own   

    existing_credits                          job num_dependents  \
995                1         'unskilled resident'              1   
996                1  'high qualif/self emp/mgmt'              1   
997                1                      skilled              1   
998                1                      skilled              1   
999                1                      skilled              1   

     own_telephone foreign_worker class  
995           none            yes  good  
996            yes            yes  good  
997           none            yes  good  
998            yes            yes   bad  
999           none            yes  good  

[5 rows x 21 columns]

In [51]:
# Filtrar por nome da coluna
dados[["duration"]]

duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [53]:
# Filtrar linhas por indices
dados.loc[2:5]

checking_status  duration                    credit_history  \
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   
5   'no checking'        36                   'existing paid'   

               purpose  credit_amount      savings_status employment  \
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   
5            education           9055  'no known savings'     1<=X<4   

   installment_commitment personal_status other_parties  ...  \
2                       2   'male single'          none  ...   
3                       2   'male single'     guarantor  ...   
4                       3   'male single'          none  ...   
5                       2   'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   
5  'no known property'  35                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  
5  'unskilled resident'              2            yes            yes  good  

[4 rows x 21 columns]

In [54]:
# Filtro
dados.loc[dados['purpose'] == "radio/tv"]

checking_status  duration                    credit_history   purpose  \
0                <0         6  'critical/other existing credit'  radio/tv   
1          0<=X<200        48                   'existing paid'  radio/tv   
8     'no checking'        12                   'existing paid'  radio/tv   
12         0<=X<200        12                   'existing paid'  radio/tv   
15               <0        24                   'existing paid'  radio/tv   
..              ...       ...                               ...       ...   
989        0<=X<200        24  'critical/other existing credit'  radio/tv   
991   'no checking'        15                        'all paid'  radio/tv   
992              <0        18                   'existing paid'  radio/tv   
997   'no checking'        12                   'existing paid'  radio/tv   
998              <0        45                   'existing paid'  radio/tv   

     credit_amount      savings_status employment  installment_commitment  \
0             1169  'no known savings'        >=7                       4   
1             5951                <100     1<=X<4                       2   
8             3059              >=1000     4<=X<7                       2   
12            1567                <100     1<=X<4                       1   
15            1282          100<=X<500     1<=X<4                       4   
..             ...                 ...        ...                     ...   
989           1743                <100        >=7                       4   
991           1569          100<=X<500        >=7                       4   
992           1936  'no known savings'     4<=X<7                       2   
997            804                <100        >=7                       4   
998           1845                <100     1<=X<4                       4   

          personal_status other_parties  ...   property_magnitude age  \
0           'male single'          none  ...        'real estate'  67   
1    'female div/dep/mar'          none  ...        'real estate'  22   
8          'male div/sep'          none  ...        'real estate'  61   
12   'female div/dep/mar'          none  ...                  car  22   
15   'female div/dep/mar'          none  ...                  car  32   
..                    ...           ...  ...                  ...  ..   
989         'male single'          none  ...     'life insurance'  48   
991         'male single'          none  ...                  car  34   
992        'male mar/wid'          none  ...                  car  23   
997         'male single'          none  ...                  car  38   
998         'male single'          none  ...  'no known property'  23   

     other_payment_plans     housing existing_credits                   job  \
0                   none         own                2               skilled   
1                   none         own                1               skilled   
8                   none         own                1  'unskilled resident'   
12                  none         own                1               skilled   
15                  none         own                1  'unskilled resident'   
..                   ...         ...              ...                   ...   
989                 none         own                2  'unskilled resident'   
991                 bank         own                1  'unskilled resident'   
992                 none        rent                2  'unskilled resident'   
997                 none         own                1               skilled   
998                 none  'for free'                1               skilled   

    num_dependents  own_telephone foreign_worker class  
0                1            yes            yes  good  
1                1           none            yes   bad  
8                1           none            yes  good  
12               1            yes            yes  good  
15               1           none          

In [57]:
# Atribuindo resultado a variavel, criando outro df
credito2 = dados.loc[dados['credit_amount'] > 18000]
print(credito2)

    checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]


In [60]:
# Definindo apenas algumas colunas
credito3 = dados[['checking_status', 'duration']].loc[dados['credit_amount'] > 18000]
print(credito3)

    checking_status  duration
915        0<=X<200        48


In [63]:
# Séries, única coluna
# Pode ser criada a partir de listas, array do numpy ou coluna de dataframe
s1 = pd.Series([2,5,3,34,54,23,1,16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


In [64]:
# Serie a partir de um array do numpy
array = np.array([2,5,3,34,54,23,1,16])
s2 = pd.Series(array)
print(s2)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


In [71]:
# Serie a partir de um dataframe
s3 = dados['purpose']
print(s3)
print(f"Tipo: {type(s3)}")

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...         
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object
Tipo: <class 'pandas.core.series.Series'>


In [81]:
# Note a diferença, temos um dataframe
d4 = dados[['purpose']]
print(d4)
print(f"Tipo: {type(d4)}")

                 purpose
0               radio/tv
1               radio/tv
2              education
3    furniture/equipment
4              'new car'
..                   ...
995  furniture/equipment
996           'used car'
997             radio/tv
998             radio/tv
999           'used car'

[1000 rows x 1 columns]
Tipo: <class 'pandas.core.frame.DataFrame'>


In [92]:
# Renomeando
dados.rename(columns={"duration":"duração","purpose":"propósito"}, inplace=True) #inplace: persiste na mudança
dados.head()

duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
4       24              'delayed previously'            'new car'   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   
1           5951                <100     1<=X<4                       2   
2           2096                <100     4<=X<7                       2   
3           7882                <100     4<=X<7                       2   
4           4870                <100     1<=X<4                       3   

        personal_status other_parties  residence_since   property_magnitude  \
0         'male single'          none                4        'real estate'   
1  'female div/dep/mar'          none                2        'real estate'   
2         'male single'          none                3        'real estate'   
3         'male single'     guarantor                4     'life insurance'   
4         'male single'          none                4  'no known property'   

   age other_payment_plans     housing  existing_credits  \
0   67                none         own                 2   
1   22                none         own                 1   
2   49                none         own                 1   
3   45                none  'for free'                 1   
4   53                none  'for free'                 2   

                    job  num_dependents own_telephone foreign_worker class  
0               skilled               1           yes            yes  good  
1               skilled               1          none            yes   bad  
2  'unskilled resident'               2          none            yes  good  
3               skilled               2          none            yes  good  
4               skilled               2          none            yes   bad

In [ ]:
# Excluir coluna
dados.drop('checking_status',axis=1, inplace=True)
print(dados)

In [97]:
dados.head()

duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
4       24              'delayed previously'            'new car'   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   
1           5951                <100     1<=X<4                       2   
2           2096                <100     4<=X<7                       2   
3           7882                <100     4<=X<7                       2   
4           4870                <100     1<=X<4                       3   

        personal_status other_parties  residence_since   property_magnitude  \
0         'male single'          none                4        'real estate'   
1  'female div/dep/mar'          none                2        'real estate'   
2         'male single'          none                3        'real estate'   
3         'male single'     guarantor                4     'life insurance'   
4         'male single'          none                4  'no known property'   

   age other_payment_plans     housing  existing_credits  \
0   67                none         own                 2   
1   22                none         own                 1   
2   49                none         own                 1   
3   45                none  'for free'                 1   
4   53                none  'for free'                 2   

                    job  num_dependents own_telephone foreign_worker class  
0               skilled               1           yes            yes  good  
1               skilled               1          none            yes   bad  
2  'unskilled resident'               2          none            yes  good  
3               skilled               2          none            yes  good  
4               skilled               2          none            yes   bad

In [98]:
# Verificar dados nulos
dados.isnull()

duração  credit_history  propósito  credit_amount  savings_status  \
0      False           False      False          False           False   
1      False           False      False          False           False   
2      False           False      False          False           False   
3      False           False      False          False           False   
4      False           False      False          False           False   
..       ...             ...        ...            ...             ...   
995    False           False      False          False           False   
996    False           False      False          False           False   
997    False           False      False          False           False   
998    False           False      False          False           False   
999    False           False      False          False           False   

     employment  installment_commitment  personal_status  other_parties  \
0         False                   False            False          False   
1         False                   False            False          False   
2         False                   False            False          False   
3         False                   False            False          False   
4         False                   False            False          False   
..          ...                     ...              ...            ...   
995       False                   False            False          False   
996       False                   False            False          False   
997       False                   False            False          False   
998       False                   False            False          False   
999       False                   False            False          False   

     residence_since  property_magnitude    age  other_payment_plans  housing  \
0              False               False  False                False    False   
1              False               False  False                False    False   
2              False               False  False                False    False   
3              False               False  False                False    False   
4              False               False  False                False    False   
..               ...                 ...    ...                  ...      ...   
995            False               False  False                False    False   
996            False               False  False                False    False   
997            False               False  False                False    False   
998            False               False  False                False    False   
999            False               False  False                False    False   

     existing_credits    job  num_dependents  own_telephone  foreign_worker  \
0               False  False           False          False           False   
1               False  False           False          False           False   
2               False  False           False          False           False   
3               False  False           False          False           False   
4               False  False           False          False           False   
..                ...    ...             ...            ...             ...   
995             False  False           False          False           False   
996             False  False           False          False           False   
997             False  False           False          False           False   
998             False  False           False          False           False   
999             False  False           False          False           False   

     class  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
995  False  
996  False  
997  False  
998  False  
999  False  

[1000 rows x 20 columns]

In [99]:
# Verificar total de dados nulos
dados.isnull().sum()

duração                   0
credit_history            0
propósito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [100]:
# Retirar colunas com NaN
dados.dropna()

duração                    credit_history            propósito  \
0          6  'critical/other existing credit'             radio/tv   
1         48                   'existing paid'             radio/tv   
2         12  'critical/other existing credit'            education   
3         42                   'existing paid'  furniture/equipment   
4         24              'delayed previously'            'new car'   
..       ...                               ...                  ...   
995       12                   'existing paid'  furniture/equipment   
996       30                   'existing paid'           'used car'   
997       12                   'existing paid'             radio/tv   
998       45                   'existing paid'             radio/tv   
999       45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4   
1             5951                <100      1<=X<4                       2   
2             2096                <100      4<=X<7                       2   
3             7882                <100      4<=X<7                       2   
4             4870                <100      1<=X<4                       3   
..             ...                 ...         ...                     ...   
995           1736                <100      4<=X<7                       3   
996           3857                <100      1<=X<4                       4   
997            804                <100         >=7                       4   
998           1845                <100      1<=X<4                       4   
999           4576          100<=X<500  unemployed                       3   

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'   
1    'female div/dep/mar'          none                2        'real estate'   
2           'male single'          none                3        'real estate'   
3           'male single'     guarantor                4     'life insurance'   
4           'male single'          none                4  'no known property'   
..                    ...           ...              ...                  ...   
995  'female div/dep/mar'          none                4        'real estate'   
996        'male div/sep'          none                4     'life insurance'   
997         'male single'          none                4                  car   
998         'male single'          none                4  'no known property'   
999         'male single'          none                4                  car   

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2   
1     22                none         own                 1   
2     49                none         own                 1   
3     45                none  'for free'                 1   
4     53                none  'for free'                 2   
..   ...                 ...         ...               ...   
995   31                none         own                 1   
996   40                none         own                 1   
997   38                none         own                 1   
998   23                none  'for free'                 1   
999   27                none         own                 1   

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes   
1                        skilled               1          none            yes   
2           'unskilled resident'               2          none            yes   
3                        skilled               2          none            yes   
4                        skilled               2          none            yes   
..         

In [103]:
# Preencher dados faltantes
dados['duração'].fillna(0,inplace=True)
dados.head()

duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
4       24              'delayed previously'            'new car'   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   
1           5951                <100     1<=X<4                       2   
2           2096                <100     4<=X<7                       2   
3           7882                <100     4<=X<7                       2   
4           4870                <100     1<=X<4                       3   

        personal_status other_parties  residence_since   property_magnitude  \
0         'male single'          none                4        'real estate'   
1  'female div/dep/mar'          none                2        'real estate'   
2         'male single'          none                3        'real estate'   
3         'male single'     guarantor                4     'life insurance'   
4         'male single'          none                4  'no known property'   

   age other_payment_plans     housing  existing_credits  \
0   67                none         own                 2   
1   22                none         own                 1   
2   49                none         own                 1   
3   45                none  'for free'                 1   
4   53                none  'for free'                 2   

                    job  num_dependents own_telephone foreign_worker class  
0               skilled               1           yes            yes  good  
1               skilled               1          none            yes   bad  
2  'unskilled resident'               2          none            yes  good  
3               skilled               2          none            yes  good  
4               skilled               2          none            yes   bad

In [104]:
# iloc
dados.iloc[0:3,0:5] # Linhas, Colunas


duração                    credit_history  propósito  credit_amount  \
0        6  'critical/other existing credit'   radio/tv           1169   
1       48                   'existing paid'   radio/tv           5951   
2       12  'critical/other existing credit'  education           2096   

       savings_status  
0  'no known savings'  
1                <100  
2                <100

In [105]:
dados.iloc[[0,1,2,3,7], 0:5]

duração                    credit_history            propósito  \
0        6  'critical/other existing credit'             radio/tv   
1       48                   'existing paid'             radio/tv   
2       12  'critical/other existing credit'            education   
3       42                   'existing paid'  furniture/equipment   
7       36                   'existing paid'           'used car'   

   credit_amount      savings_status  
0           1169  'no known savings'  
1           5951                <100  
2           2096                <100  
3           7882                <100  
7           6948                <100